USE ROLE CHEETAH_ROLE;
USE DATABASE CHEETAH_DB;
USE SCHEMA GOLD_BUSINESS_DATA;


CREATE OR REPLACE CORTEX SEARCH SERVICE TARGET_PDF_SEARCH
    ON CHUNK_TEXT
    ATTRIBUTES SOURCE_FILE
    WAREHOUSE = CHEETAH_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT
        CHUNK_ID,
        CHUNK_TEXT,
        SOURCE_FILE
    FROM CHEETAH_DB.GOLD_BUSINESS_DATA.TARGET_PDF_CHUNKS
);

SHOW CORTEX SEARCH SERVICES IN SCHEMA CHEETAH_DB.gold_business_data;