USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS CHEETAH_ROLE;
GRANT ROLE CHEETAH_ROLE TO USER CHEETAH;

CREATE WAREHOUSE IF NOT EXISTS CHEETAH_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE CHEETAH_WH TO ROLE CHEETAH_ROLE;

CREATE DATABASE IF NOT EXISTS CHEETAH_DB;
GRANT OWNERSHIP ON DATABASE CHEETAH_DB TO ROLE CHEETAH_ROLE;

CREATE STORAGE INTEGRATION IF NOT EXISTS JD57922_STORAGE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = 'befd7f93-cf9d-450f-aeb9-b71889f63327'
  STORAGE_ALLOWED_LOCATIONS = ('azure://jdobbinsutaustin.blob.core.windows.net/project-raw/');

GRANT USAGE ON INTEGRATION JD57922_STORAGE_INTEGRATION TO ROLE CHEETAH_ROLE;

USE ROLE CHEETAH_ROLE;
USE WAREHOUSE CHEETAH_WH;
USE DATABASE CHEETAH_DB;

CREATE SCHEMA IF NOT EXISTS RAW_BUSINESS_DATA;
USE SCHEMA RAW_BUSINESS_DATA;

CREATE OR REPLACE FILE FORMAT RAW_BUSINESS_DATA.RAW_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 0
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  ESCAPE_UNENCLOSED_FIELD = NONE
  EMPTY_FIELD_AS_NULL = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;


CREATE OR REPLACE STAGE RAW_BUSINESS_DATA.RAW_AZURE_STAGE
  STORAGE_INTEGRATION = JD57922_STORAGE_INTEGRATION
  URL = 'azure://jdobbinsutaustin.blob.core.windows.net/project-raw/'
  FILE_FORMAT = RAW_BUSINESS_DATA.RAW_CSV_FORMAT;

LIST @RAW_BUSINESS_DATA.RAW_AZURE_STAGE;


CREATE OR REPLACE TRANSIENT TABLE RAW_BUSINESS_DATA.RAW_BUSINESS_DATA (
  RAW_ROW       VARCHAR,
  SOURCE_FILE   VARCHAR,
  LOAD_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TRANSIENT TABLE RAW_BUSINESS_DATA.RAW_STORE_DETAILS (
  RAW_ROW       VARCHAR,
  SOURCE_FILE   VARCHAR,
  LOAD_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


COPY INTO RAW_BUSINESS_DATA.RAW_BUSINESS_DATA (RAW_ROW, SOURCE_FILE)
  FROM (
    SELECT $1, METADATA$FILENAME
    FROM @RAW_BUSINESS_DATA.RAW_AZURE_STAGE/raw_business_data.csv
  )
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = NONE SKIP_HEADER = 0)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_BUSINESS_DATA.RAW_STORE_DETAILS (RAW_ROW, SOURCE_FILE)
  FROM (
    SELECT $1, METADATA$FILENAME
    FROM @RAW_BUSINESS_DATA.RAW_AZURE_STAGE/raw_store_details.csv
  )
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = NONE SKIP_HEADER = 0)
  ON_ERROR = 'CONTINUE';


CREATE SCHEMA IF NOT EXISTS SILVER_BUSINESS_DATA;
USE SCHEMA SILVER_BUSINESS_DATA;


CREATE OR REPLACE TABLE SILVER_BUSINESS_DATA.STORE_INFO AS
SELECT * FROM (
  SELECT
    SPLIT_PART(RAW_ROW, ',', 1)::INT AS STORE_ID,
    SPLIT_PART(RAW_ROW, ',', 2) AS STORE_TYPE,
    TRIM(SPLIT_PART(SPLIT_PART(RAW_ROW, '"', 2), ',', 1)) AS STREET,
    TRIM(SPLIT_PART(SPLIT_PART(RAW_ROW, '"', 2), ',', 2)) AS CITY,
    TRIM(SPLIT_PART(SPLIT_PART(RAW_ROW, '"', 2), ',', 3)) AS STATE,
    LPAD(SPLIT_PART(RAW_ROW, '"', 3), 5, '0') AS AREA_CODE,
    SPLIT_PART(RAW_ROW, ',', -1)::INT AS STORE_SIZE_SQFT,
    ROW_NUMBER() OVER (PARTITION BY SPLIT_PART(RAW_ROW, ',', 1) ORDER BY LOAD_TS DESC) AS RN
  FROM CHEETAH_DB.RAW_BUSINESS_DATA.RAW_STORE_DETAILS
  WHERE RAW_ROW NOT LIKE 'Store,%'
) WHERE RN = 1;


CREATE OR REPLACE TABLE SILVER_BUSINESS_DATA.STORE_METRICS AS
SELECT * FROM (
  SELECT
    SPLIT_PART(b.RAW_ROW, ',', 1) || '_' || SPLIT_PART(b.RAW_ROW, ',', 2) AS STORE_DATE_KEY,
    SPLIT_PART(b.RAW_ROW, ',', 1)::INT AS STORE_ID,
    TO_DATE(SPLIT_PART(b.RAW_ROW, ',', 2), 'YYYY-MM-DD') AS WEEK_DATE,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 3), 'NA')::FLOAT AS TEMPERATURE_F,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 4), 'NA')::FLOAT AS FUEL_PRICE,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 5), 'NA')::FLOAT AS MARKDOWN1,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 6), 'NA')::FLOAT AS MARKDOWN2,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 7), 'NA')::FLOAT AS MARKDOWN3,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 8), 'NA')::FLOAT AS MARKDOWN4,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 9), 'NA')::FLOAT AS MARKDOWN5,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 10), 'NA')::FLOAT AS CPI,
    NULLIF(SPLIT_PART(b.RAW_ROW, ',', 11), 'NA')::FLOAT AS UNEMPLOYMENT_RATE,
    CASE WHEN SPLIT_PART(b.RAW_ROW, ',', 12) = 'True' THEN TRUE ELSE FALSE END AS IS_HOLIDAY,
    s.STORE_TYPE,
    s.CITY,
    s.STATE,
    s.STORE_SIZE_SQFT,
    ROW_NUMBER() OVER (
      PARTITION BY SPLIT_PART(b.RAW_ROW, ',', 1), SPLIT_PART(b.RAW_ROW, ',', 2)
      ORDER BY b.LOAD_TS DESC
    ) AS RN
  FROM CHEETAH_DB.RAW_BUSINESS_DATA.RAW_BUSINESS_DATA b
  LEFT JOIN SILVER_BUSINESS_DATA.STORE_INFO s
    ON SPLIT_PART(b.RAW_ROW, ',', 1)::INT = s.STORE_ID
  WHERE b.RAW_ROW NOT LIKE 'Store,%'
) WHERE RN = 1;

SELECT * FROM SILVER_BUSINESS_DATA.STORE_INFO LIMIT 5;
SELECT * FROM SILVER_BUSINESS_DATA.STORE_METRICS LIMIT 5;


CREATE SCHEMA IF NOT EXISTS GOLD_BUSINESS_DATA;

CREATE OR REPLACE TABLE GOLD_BUSINESS_DATA.STORE_PERFORMANCE_SUMMARY AS
SELECT
  STORE_ID,
  STORE_TYPE,
  CITY,
  STATE,
  STORE_SIZE_SQFT,
  COUNT(*) AS TOTAL_WEEKS,
  ROUND(AVG(TEMPERATURE_F), 1) AS AVG_TEMPERATURE_F,
  ROUND(AVG(FUEL_PRICE), 3) AS AVG_FUEL_PRICE,
  ROUND(AVG(CPI), 2) AS AVG_CPI,
  ROUND(AVG(UNEMPLOYMENT_RATE), 2) AS AVG_UNEMPLOYMENT_RATE,
  SUM(CASE WHEN IS_HOLIDAY THEN 1 ELSE 0 END) AS HOLIDAY_WEEKS,
  MIN(WEEK_DATE) AS FIRST_WEEK,
  MAX(WEEK_DATE) AS LAST_WEEK
FROM CHEETAH_DB.SILVER_BUSINESS_DATA.STORE_METRICS
GROUP BY STORE_ID, STORE_TYPE, CITY, STATE, STORE_SIZE_SQFT
ORDER BY STORE_ID;


SELECT * FROM GOLD_BUSINESS_DATA.STORE_PERFORMANCE_SUMMARY LIMIT 10;
